version: "3.9"
services:
  policy:
    build: ./policy
    hostname: policy
    container_name: policy
    expose:
      - "8000/tcp"
    volumes:
      - ./policy.py:/app/server/policy.py
    #    env_file:
    #      - config.env
    restart: always
  nginx:
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    env_file:
      - config.env
    restart: always
  certbot:
    build: ./certbot
    hostname: certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    env_file:
      - config.env
    restart: always
  cron:
    build: ./cron
    hostname: cron
    container_name: cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped

volumes:
  certs:
    external: true
  certbot_acme_challenge:
