version: "3.9"
services:
  policy:
    build: ./policy
    hostname: policy
    container_name: policy
    expose:
      - "8000/tcp"
    volumes:
      - ./policy.py:/app/server/policy.py
    env_file:
      - config.env
  nginx:
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    env_file:
      - config.env
  certbot:
    build: ./certbot
    hostname: certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    env_file:
      - config.env

volumes:
  certs:
    external: true
  certbot_acme_challenge:
