version: "3.9"
services:
  policy:
    build: ./policy
    hostname: policy
    container_name: policy
    expose:
      - "8000/tcp"
    volumes:
      - ./policy.py:/app/server/policy.py
    env_file:
      - policy/policy_config.env
  nginx:
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - nginx/nginx_config.env
